---
- name: Increase the size of a disk for a Linux VM on VMWare
  become: false
  hosts: node1
  gather_facts: false

  # vars:
  #   # drive_letter: E
  #   # vm_name: greg-win-resize
  #   # vcenter_username: "{{ gen1_user }}"
  #   # vcenter_password: "{{ gen1_pword }}"
  #   # datacenter_name: Central

  tasks:
  - name: Connect to VMWare and shutdown guest
    community.vmware.vmware_guest:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      datacenter: "{{ datacenter_name }}"
      validate_certs: no
      name: "{{ vm_name }}"
      state: shutdownguest
    delegate_to: localhost
    #failed_when: vm_shutdown.instance.hw_power_status != 'poweredOff' and vm_shutdown.changed == false
    register: vm_shutdown

  - name: Wait 15 seconds
    ansible.builtin.pause:
      seconds: 15

  - name: Connect to VMWare and resize disk on VM
    community.vmware.vmware_guest_disk:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      datacenter: "{{ datacenter_name }}"
      validate_certs: no
      name: "{{ vm_name }}"
      disk:
        - size_gb: "{{ vm_disk_gb }}"
          state: present
          unit_number: 1
          scsi_controller: 0
          scsi_type: 'lsilogicsas'
    delegate_to: localhost
    register: disk_facts

  - name: Connect to VMWare and boot up guest
    community.vmware.vmware_guest:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      datacenter: "{{ datacenter_name }}"
      validate_certs: no
      name: "{{ vm_name }}"
      state: poweredon
    delegate_to: localhost
#    register: disk_facts


  - name: Debug disk info
    debug: 
      var: hostvars[inventory_hostname]["ansible_devices"]

  - name: fail if sda3 already exists
    fail:
      msg: sda3 aready exists. Aborting!
    when: hostvars[inventory_hostname]["ansible_devices"]["sda"]["partitions"]["sda3"] is defined
    tags:
      - fdisk

  - name: Partition new disk
    shell: echo -e "n\np\n3\n\n\nt\n3\n8e\nw\n" | sudo fdisk /dev/sda
    args:
      executable: /bin/bash
    become: yes
    ignore_errors: yes
    tags:
      - fdisk

  - name: partprobe
    shell: partprobe
    become: yes
    tags:
      - fdisk

  - name: update facts
    setup:

  - name: fail when sda3 does not exist
    fail:
      msg: sda3 was created successfully
    when: hostvars[inventory_hostname]["ansible_devices"]["sda"]["partitions"]["sda3"] is not defined

  - name: extend volume group onto sda3 (will take care of pvcreate) 
    lvg: 
      vg: ol
      pvs: /dev/sda2,/dev/sda3
    become: yes
    register: lvg

  - name: debug lvg
    debug:
      var: lvg
      verbosity: 1

  - name: expand lvol
    lvol:
      vg: ol
      lv: root
      size: +100%FREE
    become: yes
    register: lvol

  - name: debug lvol
    debug:
      var: lvol
      verbosity: 1

  - name: grow xfs
    filesystem:
      dev: /dev/mapper/ol-root
      fstype: xfs
      resizefs: yes
    become: yes
    register: grow_xfs

  - name: debug grow_xfs
    debug:
      var: grow_xfs



